### ISSUE TITLE
href anchor non funzionanti

### ISSUE THREAD

**Issue by KibGim** [italia/lg-competenzedigitali-docs#1]
Rivedere 
i link "ancora" nei documenti.
es: 
<a href="#id16"><span class="problematic" id="id17"><span id="id5"></span>[6]_</span></a>
nella pagina
http://lg-competenzedigitali.readthedocs.io/it/latest/doc/competenze_specialistiche/lg-competenze/rif-legislativi.html#id10

**non puntano a niente**.

**Comment by KibGim** [comment]
Ho visto @atorin ha fatto un commit e @martafalzone ha fatto un pull con "Aggiunti topic id",
gli id nella pagina linkata non vanno ancora ma immagino ci stiate lavorando.

**Comment by pdavide** [comment]
Ciao @KibGim è in programma una migrazione dei documenti verso la piattaforma [Docs Italia](https://docs.italia.it/).

Ho segnalato la issue agli owner del documento che la risolveranno in occasione della migrazione.
La riapro comunque per tenerne traccia, avevo chiuso prematuramente.

Grazie per il contributo!

**Comment by pdavide** [comment]
Closed via d3d581ff568eaa351822e98a06eef279e5a0712a.
